// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgIucLcfdkTnf2wJJEiy-fx9aDnfECbmU',
    appId: '1:973046162201:web:ff633ef938e815856e5b88',
    messagingSenderId: '973046162201',
    projectId: 'asmaa-4f152',
    authDomain: 'asmaa-4f152.firebaseapp.com',
    storageBucket: 'asmaa-4f152.firebasestorage.app',
    measurementId: 'G-H6X35JD3L8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmMl4D-I1woKiFuZ-kkcTfcEe4xTTnqjY',
    appId: '1:973046162201:android:360c158aa4856bce6e5b88',
    messagingSenderId: '973046162201',
    projectId: 'asmaa-4f152',
    storageBucket: 'asmaa-4f152.firebasestorage.app',
  );
}
